[2025-03-10T03:20:49.610+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: penguins_workflow.load_data manual__2025-03-10T03:20:43.137283+00:00 [queued]>
[2025-03-10T03:20:49.626+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: penguins_workflow.load_data manual__2025-03-10T03:20:43.137283+00:00 [queued]>
[2025-03-10T03:20:49.627+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-10T03:20:49.648+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_data> on 2025-03-10 03:20:43.137283+00:00
[2025-03-10T03:20:49.677+0000] {standard_task_runner.py:57} INFO - Started process 293 to run task
[2025-03-10T03:20:49.720+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'penguins_workflow', 'load_data', 'manual__2025-03-10T03:20:43.137283+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/penguins_workflow.py', '--cfg-path', '/tmp/tmprdze3_ei']
[2025-03-10T03:20:49.728+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask load_data
[2025-03-10T03:20:49.894+0000] {task_command.py:410} INFO - Running <TaskInstance: penguins_workflow.load_data manual__2025-03-10T03:20:43.137283+00:00 [running]> on host 14d55246a065
[2025-03-10T03:20:50.232+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='penguins_workflow' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T03:20:43.137283+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T03:20:43.137283+00:00'
[2025-03-10T03:20:50.244+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/penguins_workflow.py", line 52, in load_data
    df1 = pd.read_csv(file1)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/penguins_lter.csv'
[2025-03-10T03:20:50.334+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=penguins_workflow, task_id=load_data, execution_date=20250310T032043, start_date=20250310T032049, end_date=20250310T032050
[2025-03-10T03:20:50.357+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 23 for task load_data ([Errno 2] No such file or directory: '/data/penguins_lter.csv'; 293)
[2025-03-10T03:20:50.430+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-03-10T03:20:50.507+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
