[2025-03-10T00:11:59.048+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: penguins_workflow.clear_penguins_tables manual__2025-03-10T00:11:50.553262+00:00 [queued]>
[2025-03-10T00:11:59.081+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: penguins_workflow.clear_penguins_tables manual__2025-03-10T00:11:50.553262+00:00 [queued]>
[2025-03-10T00:11:59.082+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-10T00:11:59.115+0000] {taskinstance.py:1350} INFO - Executing <Task(MySqlOperator): clear_penguins_tables> on 2025-03-10 00:11:50.553262+00:00
[2025-03-10T00:11:59.147+0000] {standard_task_runner.py:57} INFO - Started process 2145 to run task
[2025-03-10T00:11:59.167+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'penguins_workflow', 'clear_penguins_tables', 'manual__2025-03-10T00:11:50.553262+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/penguins_workflow.py', '--cfg-path', '/tmp/tmpsspzdsja']
[2025-03-10T00:11:59.177+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask clear_penguins_tables
[2025-03-10T00:11:59.445+0000] {task_command.py:410} INFO - Running <TaskInstance: penguins_workflow.clear_penguins_tables manual__2025-03-10T00:11:50.553262+00:00 [running]> on host 1445974814ad
[2025-03-10T00:11:59.798+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='penguins_workflow' AIRFLOW_CTX_TASK_ID='clear_penguins_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:11:50.553262+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T00:11:50.553262+00:00'
[2025-03-10T00:11:59.808+0000] {sql.py:262} INFO - Executing: 
        DROP TABLE IF EXISTS penguins_raw;
        DROP TABLE IF EXISTS penguins_preprocessed;
    
[2025-03-10T00:11:59.965+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_default` isn't defined
[2025-03-10T00:11:59.996+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=penguins_workflow, task_id=clear_penguins_tables, execution_date=20250310T001150, start_date=20250310T001159, end_date=20250310T001159
[2025-03-10T00:12:00.091+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 3 for task clear_penguins_tables (The conn_id `mysql_default` isn't defined; 2145)
[2025-03-10T00:12:00.216+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-03-10T00:12:00.310+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
