[2025-03-10T00:17:03.766+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: penguins_workflow.clear_penguins_tables scheduled__2025-03-09T00:11:22.192414+00:00 [queued]>
[2025-03-10T00:17:03.785+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: penguins_workflow.clear_penguins_tables scheduled__2025-03-09T00:11:22.192414+00:00 [queued]>
[2025-03-10T00:17:03.785+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2025-03-10T00:17:03.817+0000] {taskinstance.py:1350} INFO - Executing <Task(MySqlOperator): clear_penguins_tables> on 2025-03-09 00:11:22.192414+00:00
[2025-03-10T00:17:03.848+0000] {standard_task_runner.py:57} INFO - Started process 2240 to run task
[2025-03-10T00:17:03.864+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'penguins_workflow', 'clear_penguins_tables', 'scheduled__2025-03-09T00:11:22.192414+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/penguins_workflow.py', '--cfg-path', '/tmp/tmpafvmwmjy']
[2025-03-10T00:17:03.871+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask clear_penguins_tables
[2025-03-10T00:17:04.014+0000] {task_command.py:410} INFO - Running <TaskInstance: penguins_workflow.clear_penguins_tables scheduled__2025-03-09T00:11:22.192414+00:00 [running]> on host 1445974814ad
[2025-03-10T00:17:04.258+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='penguins_workflow' AIRFLOW_CTX_TASK_ID='clear_penguins_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T00:11:22.192414+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-09T00:11:22.192414+00:00'
[2025-03-10T00:17:04.264+0000] {sql.py:262} INFO - Executing: 
        DROP TABLE IF EXISTS penguins_raw;
        DROP TABLE IF EXISTS penguins_preprocessed;
    
[2025-03-10T00:17:04.307+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_default` isn't defined
[2025-03-10T00:17:04.319+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=penguins_workflow, task_id=clear_penguins_tables, execution_date=20250309T001122, start_date=20250310T001703, end_date=20250310T001704
[2025-03-10T00:17:04.345+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 6 for task clear_penguins_tables (The conn_id `mysql_default` isn't defined; 2240)
[2025-03-10T00:17:04.406+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-03-10T00:17:04.506+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
